(def list (fn (. l) l))
(def defun (macro (name args body) (list def name (list 'fn args body))))
(def defmacro (macro (name args body) (list def name (list 'macro args body))))
(defmacro delay (x) (cons 'fn (cons () (cons x ()))))
(defmacro force (f) (cons f ()))
(defmacro let (x y b) (list (list 'fn (list x) b) y))
(defmacro -> (x f . fs) (list 'lazy-if fs (cons '-> (cons (snoc f x) fs)) (snoc f x)))
(defmacro quasiquote (x)
  (if (cons? x)
      (if (= (head x) 'unquote)
          (head (tail x))
          (list 'cons (list 'quasiquote (head x)) (list 'quasiquote (tail x))))
      (list 'quote x)))

(defun snoc (l x) (if l (cons (head l) (snoc (tail l) x)) (list x)))
(defun fac (n) (if (< 1 n) (* n (fac (- n 1))) 1))
(defun fib (n) (if (< 2 n) (+ (fib (- n 1)) (fib (- n 2))) 1))
(defun map (f l) (if l (cons (f (head l)) (map f (tail l))) ()))
(defun filter (f l)
  (if l
    (if (f (head l))
      (cons (head l) (filter f (tail l)))
      (filter f (tail l)))
    ()))
(defun fold (f a l) (if l (fold f (f a (head l)) (tail l)) a))
(defun range (m n) (if (< m n) (cons m (range (+ m 1) n)) ()))
(defun double (x) (* x 2))
(defun apply (f xs) (eval (cons f xs)))
(defun add (x . xs) (if xs (+ x (apply add xs)) x))
(defun even (x) (= (% x 2) 0))
(print (fold + 0 (range 0 10000)))
(print (-> 5 ((fn (x) (* 2 x)))))
(print (if () () (double 4)))
(print (if (fn (x) (* 2 x)) 64 34))
(print (if (fn (x) (* 2 x)) ((fn (x) (* 2 x)) ((fn (x) (+ 1 x)) 5)) ()))
(defun curry (f x) (fn (y) (f x y)))
(print (-> (range 1 10)
           (filter even)
           (map double)))
(print ((curry (fn (x y) (+ x y)) 5) 4))
(print (snoc '(1 2 3) 4))
(defun alist-get (key alist)
  (if alist
    (if (= key (head (head alist)))
      (tail (head alist))
      (alist-get key (tail alist)))
    ()))

(def pi 3)
(print (alist-get 'carrot (list (cons 'carrot 6) (cons 'apple 8))))
(print (= 'pi 'pi))
(print (env))
(let x 5 (print (alist-get 'pi (env))))

(print `(pi ,(+ 1 2)))
