(print 49)
(def list (fn (. l) l))
(def defn (macro (name args body) (list def name (list 'fn args body))))
(def defmacro (macro (name args body) (list def name (list 'macro args body))))
(defmacro delay (x) (cons 'fn (cons () (cons x ()))))
(defmacro force (f) (cons f ()))
(defmacro let (x y b) (list (list 'fn (list x) b) y))
(defmacro -> (x f . fs) (list 'lazy-if fs (cons '-> (cons (snoc f x) fs)) (snoc f x)))

(defn snoc (l x) (if l (cons (head l) (snoc (tail l) x)) (list x)))
(defn fac (n) (if (< 1 n) (* n (fac (- n 1))) 1))
(defn fib (n) (if (< 2 n) (+ (fib (- n 1)) (fib (- n 2))) 1))
(defn map (f l) (if l (cons (f (head l)) (map f (tail l))) ()))
(defn filter (f l)
  (if l
    (if (f (head l))
      (cons (head l) (filter f (tail l)))
      (filter f (tail l)))
    ()))
(defn fold (f a l) (if l (fold f (f a (head l)) (tail l)) a))
(defn range (m n) (if (< m n) (cons m (range (+ m 1) n)) ()))
(defn double (x) (* x 2))
(defn apply (f xs) (eval (cons f xs)))
(defn add (x . xs) (if xs (+ x (apply add xs)) x))
(defn even (x) (= (% x 2) 0))
(print (fold + 0 (range 0 10000)))
(print (-> 5 ((fn (x) (* 2 x)))))
(print (if () () (double 4)))
(print (if (fn (x) (* 2 x)) 64 34))
(print (if (fn (x) (* 2 x)) ((fn (x) (* 2 x)) ((fn (x) (+ 1 x)) 5)) ()))
(defn curry (f x) (fn (y) (f x y)))
(print (-> (range 1 10)
           (filter even)
           (map double)))
(print ((curry (fn (x y) (+ x y)) 5) 4))
(print (snoc '(1 2 3) 4))
